'''
This file is generated by ChatGPT 5.5-Thinking
Based on the STS2MCP mod documents and API specification.
Original documentation: https://github.com/Gennadiyev/STS2MCP/blob/main/docs/raw-full.md
'''


from __future__ import annotations

from typing import Any, Literal, Optional
import requests


GameMode = Literal["singleplayer", "multiplayer"]
ResponseFormat = Literal["json", "markdown"]
WikiItemType = Literal["all", "card", "relic"]
GameCharacter = {0: "IRONCLAD", 1: "SILENT", 2: "REGENT", 3: "NECROBINDER", 4: "DEFECT"}

class STS2ClientError(Exception):
    """Raised when the STS2_MCP API returns an error or invalid response."""


class STS2Client:
    """
    Python client for the STS2_MCP local HTTP API.

    Default base URL:
        http://localhost:15526/api/v1

    Example:
        client = STS2Client()

        state = client.get_state()
        print(state["state_type"])

        if state["state_type"] in {"monster", "elite", "boss"}:
            client.play_card(card_index=0, target="JAW_WORM_0")
            client.end_turn()
    """

    def __init__(
        self,
        base_url: str = "http://localhost:15526/api/v1",
        mode: GameMode = "singleplayer",
        timeout: float = 5.0,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.mode = mode
        self.timeout = timeout
        self.session = requests.Session()

    # -------------------------
    # Internal request helpers
    # -------------------------

    def _url(self, endpoint: str) -> str:
        endpoint = endpoint.lstrip("/")
        return f"{self.base_url}/{endpoint}"

    def _request(
        self,
        method: str,
        endpoint: str,
        *,
        params: Optional[dict[str, Any]] = None,
        json_body: Optional[dict[str, Any]] = None,
    ) -> Any:
        try:
            response = self.session.request(
                method=method,
                url=self._url(endpoint),
                params=params,
                json=json_body,
                timeout=self.timeout,
            )
        except requests.RequestException as exc:
            raise STS2ClientError(f"Request failed: {exc}") from exc

        try:
            data = response.json()
        except ValueError as exc:
            raise STS2ClientError(
                f"Non-JSON response: HTTP {response.status_code}: {response.text}"
            ) from exc

        if response.status_code >= 400:
            msg = data.get("error") or data.get("message") or str(data)
            raise STS2ClientError(f"HTTP {response.status_code}: {msg}")

        if isinstance(data, dict) and data.get("status") == "error":
            raise STS2ClientError(data.get("error", "Unknown API error"))

        return data

    def _get(self, endpoint: str, params: Optional[dict[str, Any]] = None) -> Any:
        return self._request("GET", endpoint, params=params)

    def _post(self, endpoint: str, body: dict[str, Any]) -> Any:
        return self._request("POST", endpoint, json_body=body)

    def _game_endpoint(self) -> str:
        return self.mode

    def action(self, action: str, **kwargs: Any) -> Any:
        """
        Generic action POST helper.

        Example:
            client.action("play_card", card_index=0, target="JAW_WORM_0")
        """
        body = {"action": action}
        body.update(kwargs)
        return self._post(self._game_endpoint(), body)

    # -------------------------
    # GET endpoints
    # -------------------------

    def get_state(self, format: ResponseFormat = "json") -> Any:
        """
        Read current singleplayer or multiplayer state.
        """
        return self._get(self._game_endpoint(), {"format": format})

    def get_singleplayer_state(self, format: ResponseFormat = "json") -> Any:
        return self._get("singleplayer", {"format": format})

    def get_multiplayer_state(self, format: ResponseFormat = "json") -> Any:
        return self._get("multiplayer", {"format": format})

    def get_profile(self) -> dict[str, Any]:
        return self._get("profile")

    def get_compendium(self) -> dict[str, Any]:
        return self._get("compendium")

    def search_wiki(
        self,
        query: str,
        item_type: WikiItemType = "all",
        limit: int = 10,
    ) -> dict[str, Any]:
        return self._get(
            "wiki",
            {
                "query": query,
                "item_type": item_type,
                "limit": limit,
            },
        )

    def get_profiles(self) -> dict[str, Any]:
        return self._get("profiles")

    # -------------------------
    # Profile actions
    # -------------------------

    def switch_profile(self, profile_id: int) -> Any:
        return self._post(
            "profiles",
            {
                "action": "switch",
                "profile_id": profile_id,
            },
        )

    def delete_profile(self, profile_id: int) -> Any:
        return self._post(
            "profiles",
            {
                "action": "delete",
                "profile_id": profile_id,
            },
        )

    # -------------------------
    # Menu actions
    # -------------------------

    def menu_select(self, option: str, seed: Optional[str] = None) -> Any:
        body: dict[str, Any] = {
            "option": option,
        }
        if seed is not None:
            body["seed"] = seed
        return self.action("menu_select", **body)

    # -------------------------
    # Combat actions
    # -------------------------

    def play_card(self, card_index: int, target: Optional[str] = None) -> Any:
        body: dict[str, Any] = {
            "card_index": card_index,
        }
        if target is not None:
            body["target"] = target
        return self.action("play_card", **body)

    def use_potion(self, slot: int, target: Optional[str] = None) -> Any:
        body: dict[str, Any] = {
            "slot": slot,
        }
        if target is not None:
            body["target"] = target
        return self.action("use_potion", **body)

    def discard_potion(self, slot: int) -> Any:
        return self.action("discard_potion", slot=slot)

    def end_turn(self) -> Any:
        return self.action("end_turn")

    def undo_end_turn(self) -> Any:
        """
        Multiplayer only.
        """
        return self.action("undo_end_turn")

    def combat_select_card(self, card_index: int) -> Any:
        return self.action("combat_select_card", card_index=card_index)

    def combat_confirm_selection(self) -> Any:
        return self.action("combat_confirm_selection")

    # -------------------------
    # Reward actions
    # -------------------------

    def claim_reward(self, index: int) -> Any:
        return self.action("claim_reward", index=index)

    def select_card_reward(self, card_index: int) -> Any:
        return self.action("select_card_reward", card_index=card_index)

    def skip_card_reward(self) -> Any:
        return self.action("skip_card_reward")

    def proceed(self) -> Any:
        return self.action("proceed")

    # -------------------------
    # Event actions
    # -------------------------

    def choose_event_option(self, index: int) -> Any:
        return self.action("choose_event_option", index=index)

    def advance_dialogue(self) -> Any:
        return self.action("advance_dialogue")

    # -------------------------
    # Rest site / shop / map
    # -------------------------

    def choose_rest_option(self, index: int) -> Any:
        return self.action("choose_rest_option", index=index)

    def shop_purchase(self, index: int) -> Any:
        return self.action("shop_purchase", index=index)

    def choose_map_node(self, index: int) -> Any:
        return self.action("choose_map_node", index=index)

    # -------------------------
    # Card selection overlay
    # -------------------------

    def select_card(self, index: int) -> Any:
        return self.action("select_card", index=index)

    def confirm_selection(self) -> Any:
        return self.action("confirm_selection")

    def cancel_selection(self) -> Any:
        return self.action("cancel_selection")

    # -------------------------
    # Bundle selection
    # -------------------------

    def select_bundle(self, index: int) -> Any:
        return self.action("select_bundle", index=index)

    def confirm_bundle_selection(self) -> Any:
        return self.action("confirm_bundle_selection")

    def cancel_bundle_selection(self) -> Any:
        return self.action("cancel_bundle_selection")

    # -------------------------
    # Relic / treasure actions
    # -------------------------

    def select_relic(self, index: int) -> Any:
        return self.action("select_relic", index=index)

    def skip_relic_selection(self) -> Any:
        return self.action("skip_relic_selection")

    def claim_treasure_relic(self, index: int) -> Any:
        return self.action("claim_treasure_relic", index=index)

    # -------------------------
    # Crystal Sphere actions
    # -------------------------

    def crystal_sphere_set_tool(self, tool: Literal["big", "small"]) -> Any:
        return self.action("crystal_sphere_set_tool", tool=tool)

    def crystal_sphere_click_cell(self, x: int, y: int) -> Any:
        return self.action("crystal_sphere_click_cell", x=x, y=y)

    def crystal_sphere_proceed(self) -> Any:
        return self.action("crystal_sphere_proceed")